version: '3.8'
services:
  dns:
    image: "debian:bullseye"
    container_name: DNS_CONTAINER
    tty: true
    networks:
      mype:
        ipv4_address: 192.168.1.254
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024m"
        reservations:
          cpus: "0.5"
          memory: "512m"

  web:
    image: "debian:bullseye"
    container_name: WEB_CONTAINER
    tty: true
    networks:
      mype:
        ipv4_address: 192.168.1.252
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024m"
        reservations:
          cpus: "0.5"
          memory: "512m"

  nms:
    image: "debian:bullseye"
    container_name: NMS_CONTAINER
    tty: true
    networks:
      mype:
        ipv4_address: 192.168.1.240
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024m"
        reservations:
          cpus: "0.5"
          memory: "512m"
  db:
    image: "mysql"
    container_name: MYSQL
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "tinta@1234"
      MYSQL_DATABASE: "proyecto"
      MYSQL_USER: "cesar"
      MYSQL_PASSWORD: "tinta@1234"
    networks:
      mype:
        ipv4_address: 192.168.1.251
networks:
  mype:
    name: mype5
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
